name: Cling Build and Test

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on:
      - macos-latest
    env:
      BASE_DIR:  /home/runner/work/cling/cling
      BUILD_DIR: /home/runner/work/cling/cling/build
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: root-project/llvm-project
          path: llvm
          ref: cling-latest
          fetch-depth: 1

      - name: Checkout Cling
        uses: actions/checkout@v4
        with:
          repository: root-project/cling
          path: cling
          fetch-depth: 1

      - name: Prepare build directory   
        run: |
          mkdir build

      - name: Configure
        working-directory: ${{ env.BUILD_DIR }}
        run: pwd && cmake -DLLVM_EXTERNAL_PROJECTS=cling -DLLVM_EXTERNAL_CLING_SOURCE_DIR=${{ env.BASE_DIR }}/cling/ -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="host;NVPTX" -DCMAKE_BUILD_TYPE=Release ${{ env.BASE_DIR }}/llvm/llvm/

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build . --parallel 4 --target clang cling

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: make check-cling
